version: '3.9'
services:
  postgres:
    image: postgres:11.5
    hostname: postgres
    container_name: coinmena-postgres
    environment:
      POSTGRES_DB: coinmena
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./data-test/pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    hostname: redis
    container_name: coinmena-redis
    expose:
      - "6379"

