# Generated by Django 3.1.7 on 2021-04-05 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='refreshed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Refreshed Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='crypto',
            field=models.CharField(max_length=100, verbose_name='CryptoCurrency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='fiat',
            field=models.CharField(max_length=100, verbose_name='Physical Currency'),
        ),
    ]
