# Generated by Django 3.1.7 on 2021-04-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Currency', '0002_auto_20210405_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
